sudo: required

language: rust

rust: nightly-2018-06-25

cache:
  cargo: true

services: docker

addons:
  apt:
    packages:
      - nasm
      - qemu

env:
  matrix:
    - ARCH="riscv32"
    - ARCH="x86_64"

before_script:
  - if [ $ARCH = x86_64 ]; then
    rustup component add rust-src &&
    (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update) &&
    (test -x $HOME/.cargo/bin/xargo || cargo install xargo) &&
    cargo install-update -a;
    fi

script:
  - if [ $ARCH = riscv32 ]; then
      docker run -v $(pwd):$(pwd) -w $(pwd) wangrunji0408/riscv-rust
        bash -c "cd kernel && make patch-core && make build arch=riscv32";
    elif [ $ARCH = x86_64 ]; then
      cd kernel && make build arch=x86_64;
    fi
