sudo: required

language: rust

services:
  - docker

before_install:
  - docker pull wangrunji0408/riscv-rust
  - docker run -d -v $(pwd):$(pwd) -w $(pwd) wangrunji0408/riscv-rust \
    /bin/sh -c "make build arch=riscv32"

script:
- bundle exec rake test
