sudo: required

language: rust

rust: nightly-2018-08-03

cache:
  cargo: true

addons:
  apt:
    packages:
      - nasm
      - qemu

env:
  matrix:
    - ARCH="riscv32"
    - ARCH="x86_64"

install:
  - if [ $ARCH = riscv32 ]; then
    export FILE="riscv64-unknown-elf-gcc-2018.07.0-x86_64-linux-ubuntu14";
    wget https://static.dev.sifive.com/dev-tools/$FILE.tar.gz;
    tar xf $FILE.tar.gz;
    export PATH=$PATH:$PWD/$FILE/bin;
    fi

before_script:
  - rustup component add rust-src
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/cargo-xbuild || cargo install cargo-xbuild)
  - cargo install-update -a

script:
  - cd kernel && make build arch=$ARCH
